name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4

      - name: Print debugging information before installing dependencies
        run: |
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            echo "requirements.txt not found!"
            exit 1
          fi

      - name: Install code formatter
        run: |
          python -m pip install black

      - name: Run code formatter
        run: |
          black --check .

      - name: Print debugging information after installation
        run: |
          echo "Python Version: $(python --version)"
          echo "Contents of site-packages: $(ls -l $(python -c 'import site; print(site.getsitepackages()[0])'))"
